### ISSUE TITLE
gnome shortcut

### ISSUE THREAD

**Issue by TanerXwarrior0** [wwardaww/gnome-gemini-ai#11]
is there a terminal command for launching gemini assistant? I want to use it for assign a shortcut in my gnome settings.

**Comment by wwardaww** [comment]
it's on the way, it will be available via new UI engine

**Comment by wwardaww** [comment]
You can install new ui and call via the terminal.  [instructions](https://github.com/wwardaww/gnome-gemini-ai/blob/main-beta/gui/README.md#engine-part)
