### ISSUE TITLE
Update code

### ISSUE THREAD

**Issue by martijara** [wwardaww/gnome-gemini-ai#13]
Code downloaded from GNOME Extensions does not match code on the github repository.

**Comment by wwardaww** [comment]
Which branch? Right now I'm developing a new UI engine in Rust so it's not ready to production.
but if sone commit or some features are missing on the gnome store I can push the features. can you provide which changes are missing on gnome??

**Comment by martijara** [comment]
The main branch. The latest active extension version's extension.js code does not math the github's. For example, the import methods are different on both. The latest GNOME Extension version zip file is updated to GNOME 46, but the Github's is not.

**Comment by wwardaww** [comment]
it on gnome46 branch (https://github.com/wwardaww/gnome-gemini-ai/tree/gnome46)
