### ISSUE TITLE
How can we test the new main-beta version?

### ISSUE THREAD

**Issue by Alorse** [wwardaww/gnome-gemini-ai#16]
I am writing to inquire about the availability of a beta version of your extension. I understand that the `main-beta` branch is currently in a beta stage, but it is not yet available in the official GNOME Extensions website.

I am interested in testing the beta version to provide feedback and identify any potential issues. Is there a way for me to access the beta version for testing purposes? I would be grateful if you could provide me with instructions on how to do so.

**Comment by wwardaww** [comment]
it will be available today

**Comment by wwardaww** [comment]
https://github.com/wwardaww/gnome-gemini-ai/tree/main-beta/gui#installing-the-new-ui
