### ISSUE TITLE
Error in GNOME 46.1

### ISSUE THREAD

**Issue by ThatOneCalculator** [wwardaww/gnome-gemini-ai#2]
`TypeError: this.menu.box.add is not a function`

![image](https://github.com/wwardaww/gnome-gemini-ai/assets/44733677/6fafe81f-41e3-4eb5-8c0f-11245dac8734)

Arch Linux x86_64, GNOME Shell v46.1

**Comment by zikeji** [comment]
Updating `~/.local/share/gnome-shell/extensions/geminiaiubuntu@arda.com/extension.js` and replacing `this.menu.box.add(this.scrollView);` on line 138 with `this.menu.box.add_child(this.scrollView);` has appeared to resolve the issue.

**Comment by wwardaww** [comment]
thx for reaching me, it will be into Version 18
