### ISSUE TITLE
Enhacement: Auto warp for response

### ISSUE THREAD

**Issue by Linus0080** [wwardaww/gnome-gemini-ai#7]
Hi there.

I enjoy your extension, but here is a small issue I did notice.

When a long response is being displayed, the flyout panel doesn't seems to have a maximum width and a long row of text will always stretch the panel without wrapping to a new line. Sometimes the panel will be stretched beyond the display area.

![Screenshot from 2024-05-29 09-17-18](https://github.com/wwardaww/gnome-gemini-ai/assets/66841417/b95f2870-7261-4f32-8afa-c52875ff3233)

Here is my display info if needed

Resolution: 2400*1600 (3:2)
Scaling: 200%

**Comment by wwardaww** [comment]
thanks for letting me know i will solve this issue on next release

**Comment by wwardaww** [comment]
you can track progress on https://extensions.gnome.org/review/55306
